### ISSUE TITLE
Doesn't work, outdated?

### ISSUE THREAD

**Issue by JackOfSpade** [sehmim2/YorkU_REM_Bot#1]
After installing all the dependencies, `sudo npm start` is stuck on starting server. 
I'm not sure if the IPs for the input elements changed or what, but as of Nov. 7, 2020. This script no longer works.

I'm running it on Google Cloud Platform's Virtual Machine on the open HTTP port 80.

**Comment by sehmim2** [comment]
Thank you for trying it out. I will have to fixed asap!

**Comment by sehmim** [comment]
First of all thanks for trying it out (: 

Turns out the Cron job was failing so I hard coded it to run every hour. Also it was hard coded to run only for Winter 2020. But now I have added a new parameter in .env to refers to the intended term. Also added some logs to catch errors. Hope it helps. Let me know what you thing (:
